version: "3.8"

services:
  student-service:
    image: student-service:1.0
    container_name: student-service
    build:
      context: ./student
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - university-net

  course-service:
    image: course-service:1.0
    container_name: course-service
    build:
      context: ./course
      dockerfile: Dockerfile
    ports:
      - "8082:8080"
    networks:
      - university-net

networks:
  university-net:
    driver: bridge
