apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: university-ingress

spec:
  ingressClassName: nginx
  rules:
  - host: university.local
    http:
      paths:
        - path: /api/v1/courses
          pathType: Prefix
          backend:
            service:
              name: course-service
              port:
                number: 8080
        - path: /login
          pathType: Prefix
          backend:
            service:
              name: course-service
              port:
                number: 8080
        
        - path: /api/v1/students
          pathType: Prefix
          backend:
            service:
              name: student-service
              port:
                number: 8080