name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    # checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
      
    # set up java for spring boot build
      - name: Set up java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
    # cache maven dependencies

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys:
            ${{ runner.os }}-maven-
        
      # build & test student service
      - name: Build Student Service
        run: |
          cd student
          mvn clean package -DskipTests=false

      # build & test course service
      - name: Build Course Service
        run: |
          cd course
          mvn clean package -DskipTests=false
      
      # log in to Docker hub 
      - name: Log in to the docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # Build student service docker image
      - name: build student  service docker image
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/student-service:${{ github.sha }} \
          -t ${{ secrets.DOCKER_USERNAME }}/student-service:latest \
          ./student

      # push student service docker image
      - name: push student service docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/student-service:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/student-service:latest

       # Build course service docker image
      - name: build course  service docker image
        run: |
          docker build \
          -t ${{ secrets.DOCKER_USERNAME }}/course-service:${{ github.sha }} \
          -t ${{ secrets.DOCKER_USERNAME }}/course-service:latest \
          ./course
      # push course service docker image
      - name: push course service docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/course-service:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/course-service:latest

  deploy-k8s:
    runs-on: ubuntu-latest
    needs: validate

    steps:
      - name: Checkout code
        uses: actions/checkout@v4


        # install kubectl

      - name: Set up Kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: v1.28.0

        # install kind 
      
      - name: Install kind
        uses: engineerd/setup-kind@v0.6.2
        with:
          version: v0.23.0

      # create kind cluster
      - name: Create kind cluster  
        run: |
          kind create cluster \
          --name university-cluster \
          --config k8s/kind-config.yaml
      
      - name: Install NGINX Ingress Controller
        run: |
          kubectl apply -f https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml

      - name: Wait for ingress-nginx controller
        run: |
          kubectl wait \
          --namespace ingress-nginx \
          --for=condition=Available \
          deployment/ingress-nginx-controller \
          --timeout=180s

      - name: Pull Docker images from Docker Hub
        run: |
          docker pull ${{ secrets.DOCKER_USERNAME }}/student-service:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/course-service:latest

      - name: Load Docker images into Kind
        run: |
          kind load docker-image ${{ secrets.DOCKER_USERNAME }}/student-service:latest --name university-cluster
          kind load docker-image ${{ secrets.DOCKER_USERNAME }}/course-service:latest --name university-cluster

      
      # Deploy services
      - name: Deploy to Kubernetes manifests
        run: |
          kubectl apply -f k8s/

        #wait for pods to be ready
      # Wait for application deployments
      - name: Wait for application deployments to be ready
        run: |
          kubectl wait \
            --for=condition=Available \
            deployment/course-service \
            --timeout=120s

          kubectl wait \
          --for=condition=Available \
          deployment/student-service \
          --timeout=120s


      # verify deployments
      - name: Verify Deployments
        run: |
          kubectl get deployments
          kubectl get pods
          kubectl get services
          kubectl get ingress

      - name: Smoke test via ingress
        run: |
          curl -f http://university.local/api/v1/courses/1

   
          

          
     
