name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
    # checkout repository
      - name: Checkout code
        uses: actions/checkout@v4
      
    # set up java for spring boot build
      - name: Set up java 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
    # cache maven dependencies

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys:
            ${{ runner.os }}-maven-
        
      # build & test student service
      - name: Build Student Service
        run: |
          cd student
          mvn clean package -DskipTests=false

      # build & test course service
      - name: Build Course Service
        run: |
          cd course
          mvn clean package -DskipTests=false
      
      # log in to Docker hub 
      - name: Log in to the docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      # Build student service docker image
      - name: build student  service docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/student-service:latest ./student

      # push student service docker image
      - name: push student service docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/student-service:${{ github.sha }}

       # Build course service docker image
      - name: build course  service docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/course-service:latest ./course

      # push course service docker image
      - name: push course service docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/course-service:${{ github.sha }}



      
